#!/bin/sh
#
# Sets the system time fro mthe hardware clock
#

case "$1" in
  start)
	echo -n "Setting system time: "
	echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device
	hwclock -s
	echo "OK"
	;;
  *)
	echo "Usage: $0 {start|}"
	exit 1
esac

exit $?

